### ISSUE TITLE
Publicar a versão v1.0

### ISSUE THREAD

**Issue by boidacarapreta** [boidacarapreta/adcipt20231#52]
O jogo deve preencher os seguintes requisitos:

- [x] Suporte a toque de tela #23;
- [x] Tela cheia #28;
- [x] Salas de partida #34;
- [x] Multijogador #35;
- [x] Publicação de conteúdo estático #42;
- [x] Publicação de conteúdo dinâmico #43.
- [x] Áudio sobre WebRTC #49;
- [ ] Validação em teste alfa #44.
- [x] PWA #51.
